name: 🎮 Generate Galaga Contribution Graph

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    name: 🚀 Generate Galaga
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 📥 Checkout Repository
        uses: actions/checkout@v4

      - name: 🎮 Generate Galaga Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: ITRecruitersachin
          github_token: ${{ secrets.GITHUB_TOKEN }}
          games: "galaga"

      - name: 📤 Push Generated Files
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "🎮 Update Galaga contribution graph"
          file_pattern: "output/*"
